# Generated by Django 5.1.1 on 2024-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_customuser_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('spam_count', models.IntegerField(default=0)),
                ('marked_spam_by', models.ManyToManyField(related_name='marked_spam', to='contacts.customuser')),
            ],
        ),
    ]
